const CartData =[
{
    id: 1,
    image: "/img/allpro/a1.png",
    title: "Laptop sleeve MacBook",
    price: "4459.00",
    description: "Organic Cotton, fairtrade certified",
    quantity: 1,
    rating: 121,
},
{
    id: 2,
    image: "/img/allpro/a2.png",
    title: "Laptop sleeve MacBook",
    price: "59.00",
    description: "Organic Cotton, fairtrade certified",
    quantity: 1,
    rating: 121,
},
{
    id: 3,
    image: "/img/allpro/a3.png",
    title: "Laptop sleeve MacBook",
    price: "59.00",
    description: "Organic Cotton, fairtrade certified",
    quantity: 1,
    rating: 121,
},
{
    id: 4,
    image: "/img/allpro/a4.png",
    title: "Laptop sleeve MacBook",
    price: "59.00",
    description: "Organic Cotton, fairtrade certified",
    quantity: 1,
    rating: 121,
},
{
    id: 5,
    image: "/img/allpro/a5.png",
    title: "Laptop sleeve MacBook",
    price: "59.00",
    description: "Organic Cotton, fairtrade certified",
    quantity: 1,
    rating: 121,
},
{
    id: 6,
    image: "/img/allpro/a6.png",
    title: "Laptop sleeve MacBook",
    price: "59.00",
    description: "Organic Cotton, fairtrade certified",
    quantity: 1,
    rating: 121,
},
{
    id: 7,
    image: "/img/allpro/a7.png",
    title: "Laptop sleeve MacBook",
    price: "59.00",
    description: "Organic Cotton, fairtrade certified",
    quantity: 1,
    rating: 121,
},
{
    id: 8,
    image: "/img/allpro/a8.png",
    title: "Laptop sleeve MacBook",
    price: "59.00",
    description: "Organic Cotton, fairtrade certified",
    quantity: 1,
    rating: 121,
},

]

export default CartData